apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do curl http://pre-env.us-east-1.elasticbeanstalk.com/; sleep 10;done"]
  restartPolicy: OnFailure
