apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: command-demo
  template:
    metadata:
      labels:
        app: command-demo
    spec:
      containers:
      - name: command-demo-container
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do curl http://20.44.173.160/; sleep 10;done"]
#       restartPolicy: OnFailure
