apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-demo
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: command-demo-container
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do curl http://10.0.181.165:8080; sleep 10;done"]
#       restartPolicy: OnFailure
