apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "for i in {1..10}; do curl http://10.10.6.7:8080/deliverycore/core; sleep 10; done"]
  restartPolicy: OnFailure
