---
apiVersion: v1
kind: Secret
metadata:
 name: myregistrykey
 namespace: default
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7ICJhdXRoIjoiWTNOcGNHOWphSFZpT2tOemFXaDFZa0F5TURJdyJ9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuOCAobGludXgpIgoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AuZXhlIgp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: test-eventhub
 labels:
   app: pulseeventsender
spec:
 replicas: 1
 selector:
   matchLabels:
     app: pulseeventsender
 template:
   metadata:
     labels:
       app: pulseeventsender
   spec:
     imagePullSecrets:
       - name: myregistrykey
     containers:
       - name: pulseeventsender
         image: csipochub/pulseeventsender:latest
         imagePullPolicy: IfNotPresent
         resources:
           limits:
             memory: "128Mi"
             cpu: "500m"
