apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "for i in {1..10}; do ping very-ni-test-aks-eventhub.servicebus.windows.net >> /ping.log; sleep 10; done"]
  restartPolicy: OnFailure
