apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "yum install -y telnet; for i in {1..10}; do ping 10.10.9.10; telnet 10.10.9.10 9200; >> /ping.log; sleep 10; done"]
  restartPolicy: OnFailure
